title: Computational Social Science Methods for Policy and Nonprofit Studies (PA397C|INF385T)
author: Ji Ma, The Lyndon B. Johnson School of Public Affairs at the University of Texas at Austin
# subtitle: 

# url: "https://ma-ji.github.io"
baseurl: "/"

footer_url: "https://github.com/pro-panda"
footer_text: "Theme by pro-panda"

# profile-picture: assets/profile.jpg
# favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Prerequisites"
   link: "prerequisites"
 - name: "Schedule"
   link: "course_schedule"
 - name: "Assignments"
   link: "assignments"
 - name: "Final"
   link: "final"
 - name: "Introduction"
   link: "index"
theme: jekyll-theme-midnight